### ISSUE TITLE
Local/Global Transaction Txn Allocator in Cross-DC Deployment Roadmap

### ISSUE THREAD

**Issue by JmPotato** [tikv/pd#2759]
RFC: [Local/Global Transaction in Cross-DC Deployment](https://docs.google.com/document/d/1t4D2M5W0dqduNTey1aTute4umuEQrKazU-ipSwFAaLM/edit#heading=h.efxhx09hxyyo) (In Chinese)
Issue: pingcap/tidb#18253

## Refactoring Phase

- [x] Wrap the election mechanism to improve its reusability to introduce the election of TSO Allocator more easily. (#2767 + #2831 + #2883)
- [x] Modify the `tso` package to be more extendable, maybe using `interface`. (#2803 + #2842 + #2859)

### New Configuration

- [x] Introduce the new DC location configuration. (#2925)
- [x] Write configuration into etcd for persistence. (#2939)
- [ ] Implement the ctl command and API to create and update the configuration.

### Allocator Manager

- [x] Introduce the new Allocator Manager to concurrently manage multi allocations in one PC server. (#2859)
- [x] Implement the basic election of the TSO Allocator. (#2894 + #2992)
- [x] Implement the election priority check. (#2953)
- [x] Implement the differentiation mechanism by using the low bits of TSO's logical part to distinguish the same TSO of different DCs. (#3267 + #3290)

### Local TSO Allocator

- [x] Implement the internal logic of the Local TSO Allocator. (#2986)

### Global TSO Allocator

- [x] Implement the new RPC methods used to synchronize TSO between PD servers. (#2988)
- [x] Be compatible with the old Global TSO Allocator. (#3033)
- [x] Implement the internal logic of the Global TSO Allocator. (#3033)
- [x] Implement the unit tests. (#3033)

### PD Client

- [x] Implement the new Local/Global TSO acquisition mechanism for PD Client. (#3045)

## Test Phase

- [x] Have an instance-level verification with TiDB.

## Notice

The goal of the refactoring phase is doing some preparation work to make the implementation phase can go smoothly and easily. Some of these ideas are not mature yet. So this roadmap's content above may change at any time during the process of development.

**Comment by lhy1024** [comment]
@JmPotato Can we close it?

**Comment by JmPotato** [comment]
> @JmPotato Can we close it?

It has not been released yet, I think we can keep it open.

**Comment by okJiang** [comment]
@JmPotato How about closing it now?👀

**Comment by JmPotato** [comment]
Close due to the stall of this project.
