### ISSUE TITLE
Use Joint Consensus

### ISSUE THREAD

**Issue by HunDunDM** [tikv/pd#2860]
## Development Task

Etcd has supported joint consensus, we need to port the change and finally support it in TiKV. This issue records the progress in PD. Please refer to [tikv/tikv#7587](https://github.com/tikv/tikv/issues/7587) for the total progress.

Development branch: [hundundm/pd/joint-wip](https://github.com/HunDunDM/pd/tree/joint-wip)

### Development progress

* [x] some preparations
* [x] replace operator.Cluster to opt.Cluster
* [x] steps
  * [x] add DemoteFollower
  * [x] add DemoteVoter
  * [x] add ChangePeerV2Enter
  * [x] add ChangePeerV2Leave
  * [x] add unit test
* [x] builder
  * [x] refine compatible builder
  * [x] add joint consensus builder
  * [x] add leave joint state operator
  * [x] refine unit test
* [x] checker
  * [x] add joint state checker
  * [x] add joint state checker unit test
  * ~~(optional) refine learner checker~~
* [x] fix original test with error

### Split PRs

* [x] some preparations
  * [x] [Merged] Update kvproto in dependencies #2729 
  * [x] [Merged] schedule: add IsFeatureSupported in Cluster Interface #2735 
  * [x] [Merged] testutil: refine operator_check #2887 
  * [x] [Merged] cluster: refine IsFeatureSupported #2889
  * [x] [Merged] client: fix typo file name #2890
  * [x] [Merged] test: refine unit test #2893
  * [x] [Merged] operator: replace operator.Cluster to opt.Cluster #2936
* [x] step
  * [x] [Merged] operator: ConfVerChanged returns uint64 #2919
  * [x] [Merged] schedule: add some operator steps related to joint consensus #2895
* [x] builder
  * [x] [Merged] operator: refactor the builder to prepare to support the joint consensus #2938
  * [x] [Merged] operator: implement joint consensus builder #2944
  * [x] [Merged] operator: optimize builder code for the previous PRs #2947
    * Unite `hasAbilityLeader` and `allowLeader `
    * Use `allowDemote` + `useJointConsensus` instead of `useJointConsensus`
    * Consider `promote learner + demote voter` as a step
    * Rename `Empty` to `IsEmpty`
    * Rename `b2i` to `BoolToInt`
    * Unite `newBuilderWithBasicCheck` and `NewBuilder`
* [x] [Merged] schedule: add joint state checker #2952
* ~~(optional) refine learner checker~~

### Update patchs

* [x] schedule: add enable-joint-consensus config #2955 
* [x] schedule: unify the naming style of builder #2956

**Comment by HunDunDM** [comment]
All tasks have been completed and the issue will be closed.
