### ISSUE TITLE
Build scheduling model with Simulink

### ISSUE THREAD

**Issue by bufferflies** [tikv/pd#3736]
## Description

you will simulate the schedule strategy in TIDB, it will apply for balancer region scheduler ,hot region scheduler.

you will use some math  and control theory to help schedule fast 、steady and accurate.

## Document Collection

- Proposal doc: ${proposal doc}
- Weekly report: ${weekly report link}

## Talent Challenge Program information

- Mentor of this issue: @bufferflies
- Recommended skills: advanced mathematics，
Matrix theory，Automatic control theory，
- Estimated Workloads: 3XL(XL, man-month)

## Milestones and action items

Milestone 1: ${milestone description}, Expected finish date: ${1XL}

- [ ] Mathematical modeling in hot region schedule in two store 
- [ ] verify module accurate 

Milestone 2: ${milestone descption}, Expected finish date: ${1Xl}

- [ ] use Modern control theory to modeling in hot region schedule to achieve MIMO control

MileStone3:${milestone descption}, Expected finish date: ${2XL}
- module can access TIDB to manage schedule strategy 
- abbreviation forward control theory like ARDC, MPC to improve scheduler   performance
