### ISSUE TITLE
Adjustable Priority Multidimensional Hot Scheduler Tasklist

### ISSUE THREAD

**Issue by nolouch** [tikv/pd#3869]
## Background
The current hotspot identification mainly uses byte and key dimensions, which are not very fit for load requests with high CPU overhead but low hard disk overhead, we plan to add QPS dimension to better describe the distribution of CPU resources.

After adding more dimension in the statistics,  the `hotspot scheduler` can extract to a multi-objective optimized problem. For example, we have a simple workload about the `IndexLoopUp` scenario:
![image](https://user-images.githubusercontent.com/6428910/125457056-01782f9b-e09c-4426-aa2a-716063790a59.png)

As you can see in the picture, the IO is very imbalanced but the QPS is balanced. In the hot read scenario, we priority to choose the QPS dimension because this scenario is CPU bound in most cases.  consider there are many cases and the priority dimension may be changed in different cases, we need to support some relative dimension statistics and make the dimension's priority or weight can be turned.
### Reformat hot statistic and hot scheduler
- [x] Support report hotspot in store heartbeat #10122 #3665
- [x] Simplify pending influence #3658
- [x] Replace move-hot-read-peer with move-hot-read-leader #3657
- [x] Statistics: use []float64 to represent hot peer loads #3591 
- [x] Statistics: replace loads with []float64 in peer info #3729

### Introduce QPS statistic
- [x] Report QPS about each type of command in RegionHeartbeat and StoreHeartbeat
        tikv/tikv#8157
        #3695
       https://github.com/pingcap/kvproto/pull/638

- [x] Avoid merging regions with high QPS #3805
- [x] scheduler: use qps priority with multi priorities in hot region scheduler #3923 
- [x] scheduler: compatibility about query info in hot scheduler #3947
- [x] scheduler: use the store qps stats in the hot-write-leader-balance #3948

#### write qps
- [x] Add more query kind in heartbeat 
https://github.com/pingcap/kvproto/pull/794
https://github.com/pingcap/kvproto/pull/795
https://github.com/tikv/pd/pull/4011
https://github.com/tikv/tikv/pull/10786

### Support multi priorities
- [x] scheduler: support multi priorities api for hot-region-scheduler #3899 
- [x] Support multi priority #3920
- [x] scheduler: set different priorities for write-leader and write-peer #3937
- [x] scheduler: fix json tag for hot region scheduler config #3942
- [x] scheduler: adjust hot region config when pd-ctl return #3982
- [x] scheduler: use compatible config after upgrading for hot-region #3981

### Reduce different dim conflict
- [x] scheduler: use pending amp in hot region scheduler #3926 
- [x] scheduler: unify leaderSolver and peerSolver in hot read scheduler #3925 

### Misc
- [x] scheduler: fix isHot check #3722
- [x] More Friendly hotspot info in API #3731 
- [x] scheduler: fix sort hot peer in hot scheduler #3741
- [x] statistic: more stable test for query test tikv/tikv#10386 
- [x] metrics: add qps metrics and remove unnecessary metrics #3954
- [x] scheduler: fix anticount and improving the Robustness of Hotspot Statistics #3928
- [x] scheduler: fix inaccurate statistics and config #3949
- [x] scheduler: consider evict leader when calc expect #3967

### Introduce the weight and priority
- TBD

### Advance
- [x] https://github.com/tikv/tikv/issues/10736

**Comment by tisonkun** [comment]
@nolouch on the [monthly meeting](https://internals.tidb.io/t/topic/363/2) @BusyJay said this feature is released in 5.2, is it true? I can see all tasks listed here is done. And if it is released, we can close this issue.

Also I'd like to know whether we write a design document for this task, or you think issue description already cover the design?

**Comment by nolouch** [comment]
yes, it is already released in 5.2. but there are some problems left and need to be cleaned up, but we can close this one at first and create a new one for the remaining issues.
the design document may only acquire in the google document, cc @lhy1024 , cloud you add a RFC for this feature?

**Comment by lhy1024** [comment]
This issue has been released in 5.2.0 and its next phase of progress was released in 6.4.0.
ref #4949
