### ISSUE TITLE
Enhance Split Table Stability and Usability

### ISSUE THREAD

**Issue by nolouch** [tikv/pd#4095]
## Description

In the [high concurrency practice of TiDB](https://docs.pingcap.com/tidb/stable/high-concurrency-best-practices), split table is a common operation for users. It can help users solve hotspot issues in advance and prevent sudden traffic from being unable to handle it.

## Document Collection

- Proposal doc: ${proposal doc}
- Weekly report: ${weekly report link}

## Talent Challenge Program information

- Mentor of this issue: @Yisaer 
- Recommended skills:  Go
- Estimated Workloads: 2XL

## Milestones and action items

Milestone 1:  Enhance the `split table` stability

- [ ] dive to the problem https://github.com/pingcap/tidb/issues/24295
- [ ] Let PD check regions before splitting regions https://github.com/tikv/pd/issues/2733
- [ ] All downstream use new API.

Milestone 2: Enhance the `split table` usability
refer: https://github.com/wentaojin/tidba, we can extend the `split table` syntax.

- [ ] TBD
- [ ] TBD
