### ISSUE TITLE
Fix unstable tests

### ISSUE THREAD

**Issue by nolouch** [tikv/pd#4160]
##  Record the unstable tests
- [x] TestStoreOverloaded https://github.com/tikv/pd/issues/3108
- [x] Data race in TestElection (https://github.com/tikv/pd/pull/4123  https://github.com/tikv/pd/pull/4102 https://github.com/tikv/pd/pull/4061)
- [x] ci failed runing too long TestWatcher https://github.com/tikv/pd/issues/4165
- [x]  Data race in TestSchedule  https://github.com/tikv/pd/issues/4159
- [x] Data race caused by priority checker https://github.com/tikv/pd/issues/4169
