### ISSUE TITLE
Tracking issue for making region size dynamic

### ISSUE THREAD

**Issue by bufferflies** [tikv/pd#4428]
### Summary:
ref: #https://github.com/tikv/tikv/issues/11515
Make the size of a region dynamic, and only set a upper limit.
This is the first step that we try to support PB scale cluster.

### Tasks：
- [x] Opeator life cycle will adjust by region size not hard code includes expired、timeout、influence. related: #4456
- [x] #4654
- [x] checker will work well after one store offline. 
- [x] PD schedules well on both size balance and load balance.
- [x] #4668
- [x] PD uses buckets to do hotspot split and deprecated TiKV local hotspot split

**Comment by lhy1024** [comment]
>TiKV/PD support processing flow report in a standalone stream.

Maybe we can use store heartbeat

**Comment by bufferflies** [comment]
> Can these tasks be closed?

yes ， closed by completed
