### ISSUE TITLE
 Tracking issue for PD own service self-protection

### ISSUE THREAD

**Issue by CabinfeverB** [tikv/pd#4480]
## Enhancement

This issue is tracking PD's own service self-protection mechanism.

The self-protection mechanism (refer to #4373) consists of two parts the standard use of etcd and the own service of PD itself. PD provides services for other components in two ways: HTTP API and gRPC. But now PD provides gRPC service by embedding etcd which is lack of a method to use gRPC interceptor, so we will support HTTP self-protection firstly.

We will develop two features to implement the self-protection mechanism. Such as k8s, hold a handler chain to process middleware. So PD will hold the rate limit handler and auditing handler. To gather some information used by the above handlers, it will also hold an information-gathering handler.

### Subtasks

- [x]  Implementing the information-gathering handler
  - [x] #4490 
  - [x] #4494 
  - [x] #4538
  - [x] #4681
- [x] Support HTTP QPS rate limit
  - [x] #4666
  - [x] #4500
- [x] Support HTTP audit 
  - [x] #4601
  - [x] #4602
  - [x] #4608
- [x] Config
  - [x] #4761
  - [x] #4869
- [ ] Let other components add `component` header
- [ ] Edit docs
### TODO
- [ ] support gRPC self-protection

**Comment by lhy1024** [comment]
@CabinfeverB Can we close it?

**Comment by CabinfeverB** [comment]
Closed since most tasks has been finished.
