### ISSUE TITLE
Reduce the dependency of `RaftCluster` for `coordinator`

### ISSUE THREAD

**Issue by rleungx** [tikv/pd#4515]
## Enhancement Task
The mutex between `RaftCluster` and `coordinator` is complicated which is easy to cause a deadlock when writing codes. We need to make it more clear and reduce the dependency of `RaftCluster` for `coordinator`.

### Subtask
- [x] https://github.com/tikv/pd/pull/4516
- [x] https://github.com/tikv/pd/pull/4544
- [x] https://github.com/tikv/pd/pull/4594
- [x] https://github.com/tikv/pd/pull/4597
