### ISSUE TITLE
Tracking Issue for Test Restructure

### ISSUE THREAD

**Issue by JmPotato** [tikv/pd#4813]
This is the tracking issue for restructuring PD tests, focusing on unit tests and integration tests, especially on unifying test infrastructure in [testify](https://github.com/stretchr/testify). See https://github.com/pingcap/tidb/issues/26022 for more details on the TiDB side. Before you start, please read the code of conduct below carefully.

## Code of Conduct

* Make the PR as small as possible.
	* Modify only one or two packages at a time if possible.
	* Only focus on the test framework migration work, do not change the test logic. If you feel there is a strong need to refactor some tests, please file an issue to work on it later.
* Carefully use the suite of testify because it runs its inside tests serially.
* If a test needs to run a mock test cluster or something that is not lightweight, it's a good idea to put several tests inside a single suite to ensure maximum resource sharing.
* If you need to call `require.Xxx(t, a, b)` multiple times, please create a `re := require.New(t)` first to avoid passing the `t` all around.
* Use only `require.Xxx` or `suite.Xxx` whenever possible, do not mix the two.
* For a function that will return `error` type, please use `require.NoError/Error` rather than `require.Nil/NotNil`.
* For an equality comparison, please place the expected value as the first argument to fit the function signature, which will make the error message clear if the test fails.
	* `re.Equal(expected, actual)` ✅
	* `re.Equal(actual, expected)` ❌
* Comment on this issue first to tell others which package you will work on.

## Migration

- [x] migrate test-infra to testify for `client` (#5081)
- [x] migrate test-infra to testify for `pkg/apiutil` (#5061)
- [x] migrate test-infra to testify for `pkg/assertutil` (#5067)
- [x] migrate test-infra to testify for `pkg/audit` (#5061)
- [x] migrate test-infra to testify for `pkg/autoscaling` (#5061)
- [x] migrate test-infra to testify for `pkg/cache` (#5061)
- [x] migrate test-infra to testify for `pkg/codec` (#5066)
- [x] migrate test-infra to testify for `pkg/encryption` (#5066)
- [x] migrate test-infra to testify for `pkg/errs` (#5066)
- [x] migrate test-infra to testify for `pkg/etcdutil` (#5067)
- [x] migrate test-infra to testify for `pkg/grpcutil` (#5067)
- [x] migrate test-infra to testify for `pkg/keyutil` (#5067)
- [x] migrate test-infra to testify for `pkg/logutil` (#5067)
- [x] migrate test-infra to testify for `pkg/metricutil` (#5067)
- [x] migrate test-infra to testify for `pkg/mock/mockhbstream` (#5086)
- [x] migrate test-infra to testify for `pkg/movingaverage` (#5086)
- [x] migrate test-infra to testify for `pkg/netutil` (#5086)
- [x] migrate test-infra to testify for `pkg/progress` (#5086)
- [x] migrate test-infra to testify for `pkg/rangetree` (#5091)
- [x] migrate test-infra to testify for `pkg/ratelimit` (#5091)
- [x] migrate test-infra to testify for `pkg/reflectutil` (#5091)
- [x] migrate test-infra to testify for `pkg/requestutil` (#5091)
- [x] migrate test-infra to testify for `pkg/slice` (#5091)
- [x] migrate test-infra to testify for `pkg/systimemon` (#5091)
- [x] migrate test-infra to testify for `pkg/typeutil` (#5091)
- [x] migrate test-infra to testify for `server`(#5198)
- [x] https://github.com/tikv/pd/issues/5199
- [x] migrate test-infra to testify for `server/cluster` (#5203)
- [x] migrate test-infra to testify for `server/config` (#5103)
- [x] migrate test-infra to testify for `server/core` (#5123)
- [x] migrate test-infra to testify for `server/election` (#5132)
- [x] migrate test-infra to testify for `server/encryptionkm` (#5136)
- [x] migrate test-infra to testify for `server/join` (#5193)
- [x] migrate test-infra to testify for `server/region_syncer` (#5141)
- [x] #5099
- [x] migrate test-infra to testify for `server/schedule`(#5196)
- [x] migrate test-infra to testify for `server/schedule/checker` (#5174)
- [x] migrate test-infra to testify for `server/schedule/filter` (#5133)
- [x] migrate test-infra to testify for `server/schedule/labeler` (#5193)
- [x] migrate test-infra to testify for `server/schedule/operator`(#5191)
- [x] #5097
- [x] #5098
- [x] #5121
- [x] migrate test-infra to testify for `server/statistics` (#5140)
- [x] migrate test-infra to testify for `server/statistics/buckets`(#5195)
- [x] migrate test-infra to testify for `server/storage` (#5139)
- [x] migrate test-infra to testify for `server/storage/kv` (#5111)
- [x] migrate test-infra to testify for `tests/autoscaling` (#5120)
- [x] migrate test-infra to testify for `tests/client` (#5081)
- [x] migrate test-infra to testify for `tests/compatibility` (#5120)
- [x] migrate test-infra to testify for `tests/dashboard` (#5120)
- [x] migrate test-infra to testify for `tests/pdbackup` (#5120)
- [x] migrate test-infra to testify for `tests/pdctl` (#5154)
- [x] migrate test-infra to testify for `tests/pdctl/cluster` (#5154)
- [x] migrate test-infra to testify for `tests/pdctl/completion` (#5154)
- [x] migrate test-infra to testify for `tests/pdctl/config` (#5154)
- [x] migrate test-infra to testify for `tests/pdctl/health` (#5154)
- [x] migrate test-infra to testify for `tests/pdctl/hot` (#5154)
- [x] migrate test-infra to testify for `tests/pdctl/label` (#5154)
- [x] migrate test-infra to testify for `tests/pdctl/log` (#5154)
- [x] migrate test-infra to testify for `tests/pdctl/member` (#5154)
- [x] migrate test-infra to testify for `tests/pdctl/operator` (#5154)
- [x] migrate test-infra to testify for `tests/pdctl/region` (#5154)
- [x] migrate test-infra to testify for `tests/pdctl/scheduler` (#5154)
- [x] migrate test-infra to testify for `tests/pdctl/store` (#5154)
- [x] migrate test-infra to testify for `tests/pdctl/tso` (#5154)
- [x] migrate test-infra to testify for `tests/pdctl/unsafe` (#5154)
- [x] migrate test-infra to testify for `tests/server`(#5197)
- [x] migrate test-infra to testify for `tests/server/api` (#5166)
- [x] migrate test-infra to testify for `tests/server/config` (#5212)
- [x] migrate test-infra to testify for `tests/server/cluster` (#5167)
- [x] migrate test-infra to testify for `tests/server/global_config` (#5227)
- [x] migrate test-infra to testify for `tests/server/id` (#5186)
- [x] migrate test-infra to testify for `tests/server/join` (#5186)
- [x] migrate test-infra to testify for `tests/server/join/join_fail` (#5186)
- [x] migrate test-infra to testify for `tests/server/member` (#5186)
- [x] migrate test-infra to testify for `tests/server/region_syncer` (#5186)
- [x] migrate test-infra to testify for `tests/server/storage` (#5166)
- [x] migrate test-infra to testify for `tests/server/tso` (#5169)
- [x] migrate test-infra to testify for `tests/server/watch` (#5186)
- [x] migrate test-infra to testify for `tools/pd-analysis/analysis` (#5149)
- [x] migrate test-infra to testify for `tools/pd-ctl/pdctl` (#5149)
- [x] migrate test-infra to testify for `tools/pd-simulator/simulator/simutil` (#5149)

## Mics

- [x] https://github.com/tikv/pd/issues/5104
- [x] https://github.com/tikv/pd/issues/5105

**Comment by LLThomas** [comment]
I will work on package "server/cluster".

**Comment by lhy1024** [comment]
I will work on the package "server/schedule/operator".

**Comment by lhy1024** [comment]
I will work on the package "server/schedule"

**Comment by LLThomas** [comment]
> I will work on the package `statistic/bucket`, `server/schedule`, `server/cluster`, `server` and `tests/server`

Hi, I have claimed the mission (server/cluster) and almost done.

**Comment by HunDunDM** [comment]
I will work on the package "pkg/btree"

**Comment by nolouch** [comment]
@LLThomas  you can modify it together. and sync with @HunDunDM to prevent conflict.

**Comment by LLThomas** [comment]
> @LLThomas you can modify it together. and sync with @HunDunDM to prevent conflict.

Okk.

**Comment by JmPotato** [comment]
Close since all tests have been migrated to the new test framework. Thank you all guys for help!
