### ISSUE TITLE
Tracking issue for the scheduling diagnosis

### ISSUE THREAD

**Issue by rleungx** [tikv/pd#5257]
## Background
Previously, when we encountered scheduling problems, it was hard to know the root cause for people unfamiliar with PD according to the existing log and monitoring. Sometimes, it's even hard for us because the scheduling has many random factors which cause the undetermined result.
Under this circumstance, we want to have an easier way to figure out why there is no expected schedule happening and why the unexpected schedule happening.

### Stage 1: support triggering diagnosis through API
- [x] https://github.com/tikv/pd/pull/5228
- [x] https://github.com/tikv/pd/pull/5266
- [x] https://github.com/tikv/pd/pull/5283
- [x] https://github.com/tikv/pd/pull/5135
- [ ] https://github.com/tikv/pd/pull/5125

### Stage 2: support continuously diagnosis
TBD
