### ISSUE TITLE
Separate scheduling into an independent service

### ISSUE THREAD

**Issue by rleungx** [tikv/pd#5839]
### Phase 1: separate the scheduler into the scheduling service 

- [x] Decouple the dependency between server and schedule (mv to `/pkg/schedule`) @rleungx 
  - [x] https://github.com/tikv/pd/pull/5792
  - [x] https://github.com/tikv/pd/pull/6133
  - [x] https://github.com/tikv/pd/pull/6481
  - [x] https://github.com/tikv/pd/pull/6491
  - [x] https://github.com/tikv/pd/pull/6490
  - [x] https://github.com/tikv/pd/pull/6489
  - [x] https://github.com/tikv/pd/pull/6503
  - [x] https://github.com/tikv/pd/pull/6418
  - [x] https://github.com/tikv/pd/pull/6857
- [x] Refactor cluster and coordinator to reduce the dependencies @rleungx
  - [x] https://github.com/tikv/pd/pull/6551
  - [x] https://github.com/tikv/pd/pull/6552
  - [x] https://github.com/tikv/pd/pull/6553
  - [x] https://github.com/tikv/pd/pull/6557
  - [x] https://github.com/tikv/pd/pull/6769
  - [x] https://github.com/tikv/pd/pull/6771
  - [x] https://github.com/tikv/pd/pull/6773
  - [x] https://github.com/tikv/pd/pull/6774
  - [x] https://github.com/tikv/pd/pull/6776
- [x] Run scheduling service independently @rleungx 
  - [x] https://github.com/tikv/pd/pull/6542
  - [x] https://github.com/tikv/pd/pull/6826
  - [x] https://github.com/tikv/pd/pull/6891
  - [x] https://github.com/tikv/pd/pull/6893
  - [x] https://github.com/tikv/pd/pull/6896
  - [x] https://github.com/tikv/pd/pull/7236
  - [x] https://github.com/tikv/pd/pull/7039
  - [x] https://github.com/tikv/pd/pull/7061
- [x] Dynamic configuration @JmPotato
  - [x] https://github.com/tikv/pd/pull/6857
  - [x] https://github.com/tikv/pd/pull/6862
  - [x] https://github.com/tikv/pd/pull/6902
  - [x] https://github.com/tikv/pd/pull/6921
  - [x] https://github.com/tikv/pd/pull/6955
  - [x] https://github.com/tikv/pd/pull/7213
  - [x] https://github.com/tikv/pd/pull/7205
  - [x] https://github.com/tikv/pd/pull/7409
- [x] Synchronize the scheduling meta @JmPotato 
  - [x] https://github.com/tikv/pd/pull/6878
  - [x] https://github.com/tikv/pd/pull/7047
  - [x] https://github.com/tikv/pd/pull/7002
  - [x] https://github.com/tikv/pd/pull/7076
  - [x] https://github.com/tikv/pd/pull/7082
- [x] Migrate HTTP APIs @lhy1024 
  - [x] https://github.com/tikv/pd/pull/6960
  - [x] https://github.com/tikv/pd/pull/6963
  - [x] https://github.com/tikv/pd/pull/6964
  - [x] https://github.com/tikv/pd/pull/7072
  - [x] https://github.com/tikv/pd/pull/7078
  - [x] https://github.com/tikv/pd/pull/7089
  - [x] https://github.com/tikv/pd/pull/7131
  - [x] https://github.com/tikv/pd/pull/7090
  - [x] https://github.com/tikv/pd/pull/7184
  - [ ] https://github.com/tikv/pd/pull/7183
  - [x] https://github.com/tikv/pd/pull/7279
  - [x] https://github.com/tikv/pd/pull/7278
  - [x] https://github.com/tikv/pd/pull/7199
  - [x] https://github.com/tikv/pd/pull/7283
  - [x] https://github.com/tikv/pd/pull/7297
  - [x] https://github.com/tikv/pd/pull/7357
- [x] Transfer essential Internal calls to gRPC
  - [x] https://github.com/tikv/pd/pull/6984
- [x] Forward heartbeat to scheduling server
  - [x] https://github.com/tikv/pd/pull/6985
  - [x] https://github.com/tikv/pd/pull/6976
  - [x] https://github.com/tikv/pd/pull/7023
  - [x] https://github.com/tikv/pd/pull/7097
  - [x] https://github.com/tikv/pd/pull/7305
- [x] Forward other gRPC requests
  - [x] https://github.com/tikv/pd/pull/7190
  - [x] https://github.com/tikv/pd/pull/7208
- [x] Migrate the metrics
  - [x] https://github.com/tikv/pd/pull/7112
  - [x] https://github.com/tikv/pd/pull/7175
  - [x] https://github.com/tikv/pd/pull/7370
- [x] Dynamic switch
  - [x] https://github.com/tikv/pd/pull/7270
  - [x] https://github.com/tikv/pd/pull/7325
- [x] Mics
  - [x] https://github.com/tikv/pd/pull/7013
  - [x] https://github.com/tikv/pd/pull/7032
  - [x] https://github.com/tikv/pd/pull/7060
  - [x] https://github.com/tikv/pd/pull/7172
  - [x] https://github.com/tikv/pd/pull/7406
- [x] Testing
  - [x] https://github.com/tikv/pd/pull/7029
  - [x] https://github.com/tikv/pd/pull/7120
  - [x] https://github.com/tikv/pd/pull/7113
  - [x] https://github.com/tikv/pd/pull/7214
  - [x] https://github.com/tikv/pd/pull/7254
  - [x] https://github.com/tikv/pd/pull/7268
  - [x] https://github.com/tikv/pd/pull/7367
  - [x] https://github.com/tikv/pd/pull/7385
  - [x] https://github.com/tikv/pd/pull/7392
  - [x] https://github.com/tikv/pd/pull/7398
  - [x] https://github.com/tikv/pd/pull/7408
  - [x] https://github.com/tikv/pd/pull/7402
  - [x] https://github.com/tikv/pd/pull/7412
  - [x] https://github.com/tikv/pd/pull/7368
  - [x] https://github.com/tikv/pd/pull/7417
  - [x] https://github.com/tikv/pd/pull/7421
  - [x] https://github.com/tikv/pd/pull/7426
  - [x] https://github.com/tikv/pd/pull/7437
  - [x] https://github.com/tikv/pd/pull/7455
  - [x] https://github.com/tikv/pd/pull/7463
  - [x] https://github.com/tikv/pd/pull/7433
  - [x] https://github.com/tikv/pd/pull/7486
  - [x] https://github.com/tikv/pd/pull/7487
  - [x] https://github.com/tikv/pd/pull/7435
  - [ ] https://github.com/tikv/pd/pull/7470
- [x] Bugfixes 
  - [x] https://github.com/tikv/pd/pull/7105
  - [x] https://github.com/tikv/pd/pull/7128
  - [x] https://github.com/tikv/pd/pull/7155
  - [x] https://github.com/tikv/pd/pull/7163
  - [x] https://github.com/tikv/pd/pull/7220
  - [x] https://github.com/tikv/pd/pull/7241
  - [x] https://github.com/tikv/pd/pull/7272
  - [x] https://github.com/tikv/pd/pull/7319
  - [x] https://github.com/tikv/pd/pull/7333
  - [x] https://github.com/tikv/pd/pull/7335
  - [x] https://github.com/tikv/pd/pull/7354
  - [x] https://github.com/tikv/pd/pull/7389
  - [x] https://github.com/tikv/pd/pull/7396
  - [x] https://github.com/tikv/pd/pull/7403
  - [x] https://github.com/tikv/pd/pull/7420
  - [x] https://github.com/tikv/pd/pull/7415
  - [x] https://github.com/tikv/pd/pull/7450
  - [x] https://github.com/tikv/pd/pull/7454
  - [ ] https://github.com/tikv/pd/pull/7481
  - [x] https://github.com/tikv/pd/pull/7472
